spring: 
  datasource:
    url: jdbc:mysql://localhost:3306/security_demo?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&pinGlobalTxToPhysicalConnection=true&autoReconnect=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: nmamtf
    
  redis: 
    database: 0
    host: 127.0.0.1
    port: 6379
    password: nmamtf333126
    pool: 
      max-active: 8
      max-wait: 1
      min-idle: 0
    timeout: 0
    
  cache: 
    type: redis
    
  session: 
    store-type: none
    
server: 
  port: 8080    
  context-path:  /securityDemoApi/rest
    
security:
  basic: 
    enabled: true
    
wlf:  
  security: 
    browser:  
      #loginPage : http://localhost/securityDemo/login.html
      loginType: JSON
      createTable: false
    validateCode: 
      imageCode: 
        imageCodeStoreMethod: REDIS
        imageCodeWidth: 160
        imageCodeLength: 6
        imageCodeType: ENGLISH_CHARACTER_NUMBER