spring: 
  datasource:
    url: jdbc:mysql://localhost:3306/security_demo?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&pinGlobalTxToPhysicalConnection=true&autoReconnect=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: nmamtf
    
  session: 
    store-type: none
    
server: 
  port: 8080    
  context-path:  /securityDemoApi/rest
    
security:
  basic: 
    enabled: true
    
wlf:  
  security: 
    browser:  
      loginPage : http://localhost/securityDemo/login.html
      loginType : JSON